USE ROOM8;
DROP PROCEDURE IF EXISTS ATUALIZA_LUGAR;
DELIMITER $$


CREATE PROCEDURE ATUALIZA_LUGAR(
IN TITULO         VARCHAR(150),
IN DESCRICAO      VARCHAR(255),
IN CEP            VARCHAR(10) ,
IN ENDERECO       VARCHAR(255),
IN NUMERO         VARCHAR(20) ,
IN COMPLEMENTO    VARCHAR(60) ,
IN BAIRRO         VARCHAR(60) ,
IN CIDADE         VARCHAR(60) ,
IN ESTADO         CHAR(2),
IN PONTO_REF      VARCHAR(60) ,
IN 	ID_LUGAR     INT(5) 
)
BEGIN

  DECLARE TITULO_         VARCHAR(150) ;
  DECLARE DESCRICAO_      VARCHAR(255) ;
  DECLARE CEP_            VARCHAR(10)  ;
  DECLARE ENDERECO_       VARCHAR(255) ;
  DECLARE NUMERO_         VARCHAR(20)  ;
  DECLARE COMPLEMENTO_    VARCHAR(60)  ;
  DECLARE BAIRRO_         VARCHAR(60)  ;
  DECLARE CIDADE_         VARCHAR(60) ;
  DECLARE ESTADO_         CHAR(2);
  DECLARE PONTO_REF_      VARCHAR(60) ;
  DECLARE ID_LUGAR_      INT(5);
  
  SET @TITULO_    =TITULO      ;
  SET @DESCRICAO_ =DESCRICAO;
  SET @CEP_       =CEP;
  SET @ENDERECO_  =ENDERECO;
  SET @NUMERO_    =NUMERO;
  SET @COMPLEMENTO_=COMPLEMENTO;
  SET @BAIRRO_    =BAIRRO;
  SET @CIDADE_    =CIDADE;
  SET @ESTADO_   = ESTADO;
  SET @PONTO_REF_ = PONTO_REF;
  SET @ID_LUGAR_ = ID_LUGAR;
  
  UPDATE LUGAR 
  SET
  
TITULO     =@TITULO_    ,
DESCRICAO = @DESCRICAO_ ,
CEP        =@CEP_        , 
ENDERECO   =@ENDERECO_    ,
NUMERO     =@NUMERO_      ,
COMPLEMENTO=@COMPLEMENTO_,
BAIRRO     =@BAIRRO_      ,
CIDADE     =@CIDADE_      ,
ESTADO     =@ESTADO_      ,
PONTO_REF  =@PONTO_REF_   
  
  WHERE LUGAR.ID_LUGAR = @ID_LUGAR_;
  
  

     
END$$
DELIMITER ;

/*
CALL ATUALIZA_LUGAR(

'ATUALIZA',
'ATUALIZA',
'99',
'Rua STUALIZA ',
'2963',
'ATUALIZA 2',
'ATUALIZA 2',
'ATUALIZA 2',
'PR',
'ATUALIZA 2',
2);

SELECT * FROM LUGAR;
*/

