DROP DATABASE ROOM8;
CREATE DATABASE ROOM8;

USE ROOM8;

CREATE TABLE USUARIO (
    ID_USUARIO  INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    CPF         VARCHAR (15) NOT NULL,
    EMAIL       VARCHAR(100)  NOT NULL ,
    SENHA       VARCHAR(100) NOT NULL,
    TP_CADASTRO CHAR(2) NULL    
);

CREATE TABLE TP_CADASTRO (
  ID_TP_CAD INT(1) NOT NULL PRIMARY KEY, 
  DESC_CAD  VARCHAR(30) NOT NULL  
);

CREATE TABLE TELEFONE (
  ID_TEL      INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USUARIO     INT(5) NOT NULL ,
  TEL_FIXO    VARCHAR(15) NULL,
  TEL_CELULAR VARCHAR(15) NULL
);

CREATE TABLE LUGAR (
  ID_LUGAR    INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USUARIO     INT(5) NOT NULL ,
  TITULO      VARCHAR(150) NOT NULL, 
  DESCRICAO   VARCHAR(255) NULL, 
  CEP         VARCHAR(10) NOT NULL,
  ENDERECO    VARCHAR(255) NULL,
  NUMERO      VARCHAR(20) NULL,
  COMPLEMENTO VARCHAR(60) NULL, 
  BAIRRO      VARCHAR(60) NULL,
  CIDADE      VARCHAR(60) NULL,
  ESTADO      CHAR(2) NULL,
  PONTO_REF   VARCHAR(60) NULL    
);

CREATE TABLE FOTOS (
ID_IMAGEM INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
LUGAR INT(5) NOT NULL ,
IMAGEM_1 LONGBLOB NULL
);