DROP PROCEDURE IF EXISTS DELETAR_USUARIO;

DELIMITER $$

CREATE PROCEDURE DELETAR_USUARIO(IN CPF VARCHAR(15))

BEGIN
  DECLARE CPF_ VARCHAR (15) ;
  DECLARE ID   VARCHAR (15) DEFAULT NULL;
  DECLARE ID_FOTO VARCHAR (15) DEFAULT NULL;

  IF  EXISTS 
  (    
    SELECT * FROM USUARIO WHERE USUARIO.CPF = CPF
  )
  THEN
    SET @ID      = (SELECT ID_USUARIO FROM USUARIO WHERE USUARIO.CPF   = CPF) ;
    SET @ID_FOTO = (SELECT ID_LUGAR FROM  LUGAR WHERE LUGAR.FK_USUARIO = @ID) ;  
    DELETE FROM USUARIO  WHERE ID_USUARIO = @ID;
    DELETE FROM TELEFONE WHERE FK_USUARIO = @ID;   
  END IF; 
   
  IF EXISTS 
  (
    SELECT ID_LUGAR FROM  LUGAR WHERE FK_USUARIO = @ID
  ) 
  THEN
    DELETE FROM FOTOS WHERE FOTOS.FK_LUGAR = @ID_FOTO ;
    DELETE FROM LUGAR WHERE FK_USUARIO     = @ID      ;  
END IF; 


END$$
DELIMITER ;

/**
call DELETAR_USUARIO(998899)
select * from telefone
SELECT * FROM USUARIO;
/
