DROP PROCEDURE IF EXISTS DELETAR_LUGAR;
DELIMITER $$

CREATE PROCEDURE DELETAR_LUGAR(
IN ID_LUGAR VARCHAR(15)
)  
BEGIN

  DECLARE ID_LUGAR_ VARCHAR(15) ;
 
  SET     @ID_LUGAR_ = ID_LUGAR ;

  DELETE FROM LUGAR WHERE LUGAR.ID_LUGAR =  @ID_LUGAR_ ;
  
  DELETE FROM FOTOS WHERE FOTOS.FK_LUGAR =  @ID_LUGAR_ ;

END$$
DELIMITER ;


/*
CALL DELETAR_LUGAR(14);

SELECT * FROM LUGAR;
UPDATE LUGAR SET LUGAR.PONTO_REF = NULL  WHERE ID_LUGAR = 15; 

SELECT * FROM FOTOS;
SELECT * FROM USUARIO;
SELECT * FROM TELEFONE;*/





