DROP DATABASE IF EXISTS room8;
CREATE DATABASE room8;
USE ROOM8;

CREATE TABLE USUARIO (
    ID_USUARIO  INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    CPF         VARCHAR (15) NOT NULL UNIQUE,
    EMAIL       VARCHAR(100)  NOT NULL ,
    SENHA       VARCHAR(100) NOT NULL,
    TP_CADASTRO CHAR(2) NULL    
);

CREATE TABLE TP_CADASTRO (
  ID_TP_CAD INT(1) NOT NULL PRIMARY KEY, 
  DESC_CAD  VARCHAR(30) NOT NULL  
);

CREATE TABLE TELEFONE (
  ID_TEL      INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FK_USUARIO  INT(5) NOT NULL ,
  TEL    VARCHAR(15) NULL
);

CREATE TABLE LUGAR (
  ID_LUGAR       INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITULO         VARCHAR(150) NOT NULL, 
  DESCRICAO      VARCHAR(255) NULL, 
  CEP            VARCHAR(10) NOT NULL,
  ENDERECO       VARCHAR(255) NULL,
  NUMERO         VARCHAR(20) NULL,
  COMPLEMENTO    VARCHAR(60) NULL, 
  BAIRRO         VARCHAR(60) NULL,
  CIDADE         VARCHAR(60) NULL,
  ESTADO         CHAR(2) NULL,
  PONTO_REF      VARCHAR(60) NULL,
  FK_USUARIO     INT(5) NOT NULL 
);

CREATE TABLE FOTOS (
ID_IMAGEM INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
IMAGEM_1 LONGBLOB NULL ,
FK_LUGAR INT(5) NOT NULL 
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TEL_ID_USR FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE LUGAR ADD CONSTRAINT FK_LUG_ID_USR FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE FOTOS ADD CONSTRAINT FK_FOT_ID_LUG FOREIGN KEY (FK_LUGAR) REFERENCES LUGAR (ID_LUGAR);
