DROP PROCEDURE IF EXISTS SELECT_USUARIO;
DELIMITER $$

CREATE PROCEDURE SELECT_USUARIO(
IN CPF VARCHAR(15)
)
BEGIN

  DECLARE CPF_ VARCHAR(15) ;

  SELECT
    USUARIO.NOME ,
    USUARIO.CPF  ,
    USUARIO.EMAIL,
    USUARIO.SENHA,
    TELEFONE.TEL ,
    TP_CADASTRO.DESC_CAD
  FROM 
    USUARIO 
  LEFT JOIN 
    TELEFONE
  ON 
    (USUARIO.ID_USUARIO = TELEFONE.FK_USUARIO)
  LEFT JOIN TP_CADASTRO
  ON 
    (TP_CADASTRO.ID_TP_CAD = USUARIO.TP_CADASTRO)
  WHERE  USUARIO.CPF = CPF;
        

END$$
DELIMITER ;

CALL SELECT_USUARIO(4545454);

        
        