DROP PROCEDURE IF EXISTS SELECT__LUGAR_LUGAR;
DELIMITER $$

CREATE PROCEDURE SELECT__LUGAR_LUGAR(
IN ID INT(5)
)

BEGIN

  DECLARE ID_ INT(5) ;
  DECLARE ID_LUGAR_ INT(5) ;
  DECLARE imagem LONGBLOB;
  
  SET @ID_ = ID; 
  SET @ID_LUGAR_ = (SELECT ID_LUGAR FROM LUGAR WHERE FK_USUARIO = @ID_);

  SELECT 
    LUGAR.TITULO      ,
    LUGAR.DESCRICAO   ,
    LUGAR.CEP         ,
    LUGAR.ENDERECO    ,
    LUGAR.NUMERO      ,
    LUGAR.COMPLEMENTO ,
    LUGAR.BAIRRO      ,
    LUGAR.CIDADE      ,
    LUGAR.ESTADO      ,
    LUGAR.PONTO_REF  
  FROM 
    LUGAR 
    
    
  WHERE LUGAR.ID_LUGAR=@ID_LUGAR_;
END$$
DELIMITER ;




/*
CALL SELECT__TODOS_LUGAR(1);

SELECT * FROM USUARIO




SELECT * FROM LUGAR;
SELECT * FROM FOTOS;
*/